<a href='https://aims-senegal.org/'> <img src='http://sn.nexteinstein.org/wp-content/uploads/sites/12/2016/07/aims_senegal.jpg' /></a>

# **Feature Selection: Filter Method**

In this notebook we look into the problem of feature selection, in which we have a large pool of ***d*** features and our goal is to select a small number of features ***k*** that will be used by our model. So our goal is to learn a model that only relies on ***k << d*** features.



## **Why do we do feature selection ?**
Models that use only a small subset of features require a
smaller memory footprint and can be applied faster. Furthermore, in applications such as medical diagnostics, obtaining each possible “feature” (e.g., test result) can be costly; therefore, a model that uses only a small number of features is desirable even at the cost of a small degradation in performance, relative to a model that uses more features.


## **How do we do feature selection ?**

Ideally, we could have tried all subsets of ***k*** out of ***d*** features and choose the subset which leads to the best performing model (using cross validation). However, such an exhaustive search is usually computationally intractable.


## **Feature selection methods:**

Moustapha covered 3 computationally feasible approaches for feature selection: L1 Regularization, Wrapper (Greedy) Methods (Forward Search & Backward Elimination) and Filter Method. While these methods
cannot guarantee finding the optimal subset, they often work reasonably well in practice.

## **Filter Method**
One of the simplest approach for feature selection is the filter method, in which we assess individual features, independently of other features, according to some quality measure. We can then select the ***k*** features that achieve the highest score (alternatively, we can decide on the number of features to select according to the value of their scores).

Many quality measures for features have been proposed in the literature. We will use [Mutual Information](https://en.wikipedia.org/wiki/Mutual_information) between the feature and the target as our measure of feature quality. Mutual information between a pair of random variables ***X*** and ***Y*** is defined as:

<img src='https://wikimedia.org/api/rest_v1/media/math/render/svg/4b37af4015d70867b9c50b9cf82e0fc3598b070c' />

Mutual information (MI) between two random variables is a non-negative value, which measures the dependency between the variables. It is equal to zero if and only if two random variables are independent, and higher values mean higher dependency.

Where D<sub>KL</sub> is the [Kullback Leibler Divergence](https://en.wikipedia.org/wiki/Kullback%E2%80%93Leibler_divergence) which is a measure of how one probability distribution is different from another. 


---
---
---
---
---

## **Setup Code**

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn import linear_model
from sklearn.preprocessing import StandardScaler, normalize
from sklearn.model_selection import cross_val_score, train_test_split, KFold 
from sklearn.metrics import mean_squared_error
from sklearn.feature_selection import mutual_info_regression

---
---
---
---
---

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


## **Data** 

We will experiment **again** with cancer mortality rates dataset from [here](https://data.world/nrippner/ols-regression-challenge). A slightly modified copy was shared with you on workplace a few days ago. Please Load the data "cancer-mortality-rate.csv" to your runtime or mount your drive and load it. The target is the column named **"TARGET_deathRate"**.

In [4]:
data = pd.read_csv('/content/drive/MyDrive/tut/cancer-mortality-rate.csv', index_col=0)
data.head()

avgAnnCount  avgDeathsPerYear  ...   BirthRate-8   BirthRate-9
0       1397.0               469  ...  1.964933e+06  1.202309e+07
1        173.0                70  ...  1.242757e+05  5.384984e+05
2        102.0                50  ...  3.742773e+04  1.395863e+05
3        427.0               202  ...  2.018191e+05  9.291432e+05
4         57.0                26  ...  4.553685e+06  3.094984e+07

[5 rows x 280 columns]

In [5]:
print('Number of Data Points: ', data.shape[0])
print('Number of Features: ', data.shape[1])

Number of Data Points:  3047
Number of Features:  280


---
---
---
---
---

## **Data Preprocessing**

In [6]:
# Deal with NaN values
# We can replace NaN values with the mean value of each feature (We will use this)
# We can also drop the columns with high percentage of NaN values
# We can drop rows that contain NaN Values
# We can use iterpolation techniques to fill the NaNs
# Which one I should use ? I don't know, you have to experiemnt 

for col in data.columns:
    if data[col].isna().sum() != 0:
        print(f"Col: {col}, Number of nan value: {data[col].isna().sum()}")
        data[col][data[col].isna()] = data[col].mean()

Col: PctSomeCol18_24, Number of nan value: 2285
Col: PctEmployed16_Over, Number of nan value: 152
Col: PctPrivateCoverageAlone, Number of nan value: 609
Col: PctSomeCol18_24-2, Number of nan value: 2285
Col: PctSomeCol18_24-3, Number of nan value: 2285
Col: PctSomeCol18_24-4, Number of nan value: 2285
Col: PctSomeCol18_24-5, Number of nan value: 2285
Col: PctSomeCol18_24-6, Number of nan value: 2285
Col: PctSomeCol18_24-7, Number of nan value: 2285
Col: PctSomeCol18_24-8, Number of nan value: 2285
Col: PctSomeCol18_24-9, Number of nan value: 2285
Col: PctEmployed16_Over-2, Number of nan value: 152
Col: PctEmployed16_Over-3, Number of nan value: 152
Col: PctEmployed16_Over-4, Number of nan value: 152
Col: PctEmployed16_Over-5, Number of nan value: 152
Col: PctEmployed16_Over-6, Number of nan value: 152
Col: PctEmployed16_Over-7, Number of nan value: 152
Col: PctEmployed16_Over-8, Number of nan value: 152
Col: PctEmployed16_Over-9, Number of nan value: 152
Col: PctPrivateCoverageAlone-2,

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()


In [7]:
# Train/Test Split with K fold cross validation 
y = data['TARGET_deathRate']
X = data.drop(columns=['TARGET_deathRate'])

In [8]:
kf = KFold(n_splits=5, random_state= 42, shuffle=True) 

# KFold training helper function
def KFold_train(model, X, Y, kf):
    
    scores = []

    for train_index, val_index in kf.split(X): #we split the train to K-Folds
        
        x_train, x_val = X.loc[train_index], X.loc[val_index]
        y_train, y_val = Y.loc[train_index], Y.loc[val_index]

        # Normalize the features
        mu = x_train.mean()
        std = x_train.std()

        x_train_norm = (x_train - mu) / std
        x_val_norm = (x_val - mu) / std

        # fit
        model.fit(x_train_norm, y_train)

        # evaluate
        pred_y = model.predict(x_val_norm)

        # compute the loss
        scores.append(mean_squared_error(y_val, pred_y))
    
    return np.mean(np.array(scores))

---
---
---
---
---

##  **Fit a Linear Regression model on all the features**

In [9]:
# Define the model ===> un regularized linear regression model
model = linear_model.LinearRegression(fit_intercept=True)

# Finding the model params ===> Basically solving OLS problem
# using K-fold cross validation to estimate the perfromance (MSE)
mean_mse = KFold_train(model, X, y, kf)

print(' Mean MSE error of the model: ', mean_mse)

 Mean MSE error of the model:  9508998098727.594


In [10]:
model.coef_

array([-1.37418623e+02,  1.63917545e+02,  4.49598942e+04, -5.66797398e+01,
       -5.57802098e+01, -1.57787210e+03, -1.94659431e+01,  5.01488778e+02,
       -1.82473216e+05,  2.12667682e+05, -1.31499348e+03,  1.74351844e+05,
       -1.62782719e+02, -7.17968432e+02,  1.10258485e+03, -1.35555814e+01,
       -1.98984108e+04,  1.11192148e+02,  2.12399219e+05, -5.94685251e+00,
       -9.17143146e+03, -3.11822920e+04,  5.61521159e+03, -2.08419380e+04,
        5.66216175e+02,  1.30396852e+04,  4.40612691e+01, -6.80737320e+00,
       -3.98538657e+00, -6.14583588e+04, -1.57758564e+02,  2.57773357e+03,
       -2.69990892e+04,  1.78375464e+05, -9.25877257e+05,  3.59255163e+06,
       -8.61174094e+06,  1.05270363e+07, -4.70649792e+06, -2.02734533e+03,
        1.42387201e+04, -4.25412857e+04,  7.26570240e+02, -1.82797488e-01,
        1.47580062e-01,  4.83421110e-01, -2.56955289e-01, -3.64864327e+05,
        1.53682743e+06, -4.54570252e+06,  9.54962927e+06, -1.34557327e+07,
        1.19573433e+07, -

---
---
---
---
---

##  **Fit a Linear Regression model with L1 regularization on all the features**

In [11]:
# Define the model ===> Lasso is just linear regression + l1 reg (check the sklearn docs)
model = linear_model.Lasso(alpha=0.1, fit_intercept=True, max_iter=5000)

# Finding the model params ===> Basically solving the objective (1 / (2 * n_samples)) * ||y - Xw||^2_2 + alpha * ||w||_1
# using K-fold cross validation to estimate the perfromance (MSE)
mean_mse = KFold_train(model, X, y, kf)

print(' Mean MSE error of the model: ', mean_mse)

 Mean MSE error of the model:  497.6300219562386


---
---
---
---
---

let's see how many features are actually used by the L1 regularized model

In [12]:
# to do print the model parameters (Hint: use model.coef_) and see how many of them are larger than 0.1 (in absolute value)
model.coef_
x = model.coef_
sum = x[np.where(abs(x)>0.1)]

print(len(sum))

# Your code 

68


---
---
---
---
---

### **Feature selection with Filter method**



*   Calculate the mutual information score between each feature column and the target column (use: mutual_info_regression from sklearn)
Bonus: if you implemented it yourself.

*   Now it's up to you to decide how to proceed:

*    you can take the top k features based on MI.   

*    you can choose the features that above a specified threshold based on MI scores.

*    you can do further feature selection by doing wrapper methods on top of the k selected features.

**TASK: Train a linear model on your selected set of features and compute the performance, compare your results with the L1 regularized model above.**

P.S: I got a Mean MSE error of a model = 599.05 with training on only 2 features.



In [13]:
mutual_info_regression(X,y)

array([1.26980036e-01, 1.15462043e-01, 1.52929282e-01, 1.56983814e-01,
       9.67380625e-02, 1.69097742e-01, 2.97777185e-02, 1.98784375e-02,
       2.11808640e-02, 4.29647657e-02, 3.66224639e-02, 5.29940130e-02,
       1.12867420e-02, 1.69781254e-02, 1.15855108e-02, 7.94737531e-02,
       1.58555454e-01, 1.91269757e-01, 1.16848148e-01, 9.70365241e-02,
       1.45515764e-01, 8.70782918e-02, 7.08920904e-02, 1.17008213e-01,
       1.69829741e-01, 2.83631812e-02, 7.26680137e-02, 7.04127103e-02,
       2.65009673e-02, 5.78420725e-02, 1.77816868e-02, 7.70104816e-02,
       3.08782151e-02, 2.07083256e-02, 8.18454990e-03, 8.11102609e-03,
       0.00000000e+00, 2.31186977e-03, 3.52863284e-04, 7.09598881e-02,
       3.10619979e-02, 2.51875059e-02, 1.69632731e-02, 3.13409421e-02,
       5.46415809e-02, 3.99242430e-02, 7.92533613e-02, 1.55989562e-01,
       1.61896126e-01, 1.66962606e-01, 1.45142499e-01, 1.24208349e-01,
       1.12208955e-01, 1.02317994e-01, 8.95875331e-02, 1.50905883e-01,
      

In [14]:
X_frame = mutual_info_regression(X,y) > 0.15

In [15]:
X_frame

array([False, False,  True,  True, False,  True, False, False, False,
       False, False, False, False, False, False, False,  True,  True,
       False, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True, False, False, False, False,
       False,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
        True,  True, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [16]:
new_features = X.columns[X_frame]

In [17]:
new_features

Index(['incidenceRate', 'medIncome', 'povertyPercent', 'PctHS25_Over',
       'PctBachDeg25_Over', 'PctPublicCoverageAlone', 'incidenceRate-2',
       'incidenceRate-3', 'incidenceRate-4', 'medIncome-2', 'medIncome-3',
       'povertyPercent-2', 'povertyPercent-3', 'povertyPercent-4',
       'povertyPercent-6', 'PctHS25_Over-2', 'PctHS25_Over-3',
       'PctBachDeg25_Over-2', 'PctBachDeg25_Over-3', 'PctBachDeg25_Over-4',
       'PctBachDeg25_Over-5', 'PctBachDeg25_Over-6',
       'PctPublicCoverageAlone-2', 'PctPublicCoverageAlone-3',
       'PctPublicCoverageAlone-4', 'PctPublicCoverageAlone-5'],
      dtype='object')

In [18]:
list(new_features)

['incidenceRate',
 'medIncome',
 'povertyPercent',
 'PctHS25_Over',
 'PctBachDeg25_Over',
 'PctPublicCoverageAlone',
 'incidenceRate-2',
 'incidenceRate-3',
 'incidenceRate-4',
 'medIncome-2',
 'medIncome-3',
 'povertyPercent-2',
 'povertyPercent-3',
 'povertyPercent-4',
 'povertyPercent-6',
 'PctHS25_Over-2',
 'PctHS25_Over-3',
 'PctBachDeg25_Over-2',
 'PctBachDeg25_Over-3',
 'PctBachDeg25_Over-4',
 'PctBachDeg25_Over-5',
 'PctBachDeg25_Over-6',
 'PctPublicCoverageAlone-2',
 'PctPublicCoverageAlone-3',
 'PctPublicCoverageAlone-4',
 'PctPublicCoverageAlone-5']

In [19]:
new_features_df = pd.DataFrame(X, columns=list(new_features))

In [20]:
model = linear_model.LinearRegression(fit_intercept=True)

In [21]:
mean_mse = KFold_train(model, new_features_df, y, kf)

print(' Mean MSE error of the model: ', mean_mse)

 Mean MSE error of the model:  395.0555396704641


In [22]:
X_frame = mutual_info_regression(X,y)

In [44]:
K = 22

In [45]:
ind = np.argpartition(X_frame, -K)[-K:]

In [46]:
ind

array([224, 223, 169, 226, 168,  17,  24,  71,  72,  73,  16, 167, 159,
       225, 171,  47,  48,   5,  49,   3,   2, 170])

In [47]:
best_ten_col = [X.columns[i] for i in list(ind)]

In [48]:
best_ten_col

['PctPublicCoverageAlone-3',
 'PctPublicCoverageAlone-2',
 'PctBachDeg25_Over-4',
 'PctPublicCoverageAlone-5',
 'PctBachDeg25_Over-3',
 'PctBachDeg25_Over',
 'PctPublicCoverageAlone',
 'povertyPercent-2',
 'povertyPercent-3',
 'povertyPercent-4',
 'PctHS25_Over',
 'PctBachDeg25_Over-2',
 'PctHS25_Over-2',
 'PctPublicCoverageAlone-4',
 'PctBachDeg25_Over-6',
 'incidenceRate-2',
 'incidenceRate-3',
 'povertyPercent',
 'incidenceRate-4',
 'medIncome',
 'incidenceRate',
 'PctBachDeg25_Over-5']

In [49]:
with_best_ten_features = pd.DataFrame(X, columns=list(best_ten_col))

In [50]:
with_best_ten_features

PctPublicCoverageAlone-3  ...  PctBachDeg25_Over-5
0                     2744.000  ...         2.892547e+06
1                     3581.577  ...         6.027390e+06
2                     9393.931  ...         1.048576e+06
3                    15625.000  ...         6.956884e+04
4                    11697.083  ...         7.593750e+05
...                        ...  ...                  ...
3042                  2299.968  ...         8.113681e+05
3043                  5545.233  ...         2.931625e+05
3044                  4741.632  ...         3.435974e+05
3045                  2744.000  ...         6.191736e+05
3046                  2000.376  ...         4.826172e+05

[3047 rows x 22 columns]

In [51]:
model = linear_model.LinearRegression(fit_intercept=True)

In [52]:
mean_mse = KFold_train(model, with_best_ten_features, y, kf)

print(' Mean MSE error of the model: ', mean_mse)

 Mean MSE error of the model:  396.6008394260374
